(defpackage "NAPA-FFT"
  (:use "CL")
  (:export "COMPLEX-SAMPLE" "COMPLEX-SAMPLE-ARRAY"

           "FIND-FFT-FUNCTION" "%FFT" "%FFT-SCALE"
           "FFT-INSTANCE" "RESET-FFT-INSTANCE" "MAKE-FFT-INSTANCE"
           "*FFT-INSTANCE*"
           "FFT" "SFFT"
           
           "RECTANGULAR" "HANN" "BLACKMAN" "TRIANGLE"
           "BARTLETT" "GAUSSIAN" "GAUSSIAN*BARTLETT^X"
           "BLACKMAN-HARRIS" "WINDOW-VECTOR"
           "EXTRACT-WINDOW" "EXTRACT-WINDOW-INTO"
           "EXTRACT-CENTERED-WINDOW" "EXTRACT-CENTERED-WINDOW-INTO"
           "WINDOWED-FFT"))
